name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B -DskipTests package
      - name: Run tests
        run: mvn -B test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            target/*SNAPSHOT.jar
            web.config

  deploy:
    needs: build
    runs-on: windows-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8972F06AD0744029BA56777B560EA57 }}
          startup-command: "java -Dserver.port=$PORT -jar devops-migration-0.0.1-SNAPSHOT.jar"
          package: . 
