name: Deploy Java App to Azure

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Validate Azure OIDC inputs
      shell: bash
      run: |
        missing=()
        [[ -z "${{ secrets.AZURE_CLIENT_ID }}" ]] && missing+=(AZURE_CLIENT_ID)
        [[ -z "${{ secrets.AZURE_TENANT_ID }}" ]] && missing+=(AZURE_TENANT_ID)
        [[ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]] && missing+=(AZURE_SUBSCRIPTION_ID)
        if (( ${#missing[@]} > 0 )); then
          echo "::error::Missing required secrets: ${missing[*]}"
          exit 1
        fi
    
    - name: Build with Maven
      run: |
        cd Sample-Repo
        mvn clean compile package -DskipTests
    
    - name: Run tests
      run: |
        cd Sample-Repo
        mvn test
    
    - name: Locate built jar
      id: jar
      shell: bash
      run: |
        JAR_PATH=$(ls -1 Sample-Repo/target/*.jar | head -n 1)
        JAR_NAME=$(basename "$JAR_PATH")
        echo "path=$JAR_PATH" >> "$GITHUB_OUTPUT"
        echo "name=$JAR_NAME" >> "$GITHUB_OUTPUT"
        echo "Resolved jar: $JAR_NAME"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: java-app-jar
        path: ${{ steps.jar.outputs.path }}
        retention-days: 30
    
    - name: Azure Login
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v2
      with:
        auth-type: ID_TOKEN
        audience: 'api://AzureADTokenExchange'
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to Azure App Service
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'CTS-VibeAppUK51203-3'
        package: ${{ steps.jar.outputs.path }}
        startup-command: "java -jar ${{ steps.jar.outputs.name }}"

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: OWASP Dependency Check
      run: |
        cd Sample-Repo
        mvn org.owasp:dependency-check-maven:check
      continue-on-error: true
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: Sample-Repo/target/dependency-check-report.html
        retention-days: 30
