name: Deploy Java App to Azure

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        cd Sample-Repo
        mvn clean compile package -DskipTests
    
    - name: Run tests
      run: |
        cd Sample-Repo
        mvn test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: java-app-jar
        path: Sample-Repo/target/*.jar
        retention-days: 30
    
    - name: Azure Login
      if: github.ref == 'refs/heads/main'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vibecoding-java-app'
        package: 'Sample-Repo/target/*.jar'
        startup-command: 'java -jar *.jar'
        runtime-version: 'JAVA|21-java21'

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: OWASP Dependency Check
      run: |
        cd Sample-Repo
        mvn org.owasp:dependency-check-maven:check
      continue-on-error: true
    
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: Sample-Repo/target/dependency-check-report.html
        retention-days: 30
