name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and package
      run: mvn -B clean package
      working-directory: ./Sample-Repo
    
    - name: Extract project information
      id: project-info
      run: |
        NAME=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.name)
        VERSION=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
        echo "PROJECT_NAME=$NAME" >> $GITHUB_OUTPUT
        echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
      working-directory: ./Sample-Repo
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          Sample-Repo/target/${{ steps.project-info.outputs.PROJECT_NAME }}-${{ steps.project-info.outputs.PROJECT_VERSION }}.jar
        name: Release ${{ steps.project-info.outputs.PROJECT_VERSION }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload to artifact registry (if configured)
      run: |
        echo "This step would upload to your artifact registry"
        echo "Configure your specific registry credentials and endpoints"
        # Example for Maven Central or other registries:
        # mvn deploy -DskipTests
      working-directory: ./Sample-Repo
